### PR TITLE
Add basic build instructions for BSD systems.

### PR DESCRIPTION
**Pull request by ghost**
I thought it might be worth to mention that BSD systems by default supply a different version of Make program that doesn't support some language extensions imposed by the GNU version of Make.

### CODE REVIEW

**Comment by EvilPudding** [comment]
I was not aware of this, to be honest, the build system right now is a mess and very bad in terms of portability and I'm thinking of ways of re-doing. I'm surprised it even works on BSD. Thanks for pointing this out though. What are the extensions causing the problem? Updating the readme is a good short-term solution, but it would be great if we could just fix the makefiles.

**Comment by ghost** [comment]
It's a bit problematic, because I'd have to check out what non-standard features does that Makefile use and then rewrite it so it runs both on BSDs and GNU systems. However, I cannot guarantee that since, well, both versions have evolved a bit into two different things sharing a common base standard. I'll try to get it to compile properly under OpenBSD's make tommorow though. If I won't find a simple solution to make one Makefile run both on BSDs and Linux, I'll try to make a separate Makefile for BSDs.

**Comment by ghost** [comment]
Oh, and the result of running `make` on OpenBSD is:
`
make: don't know how to make CC (prerequisite of: emscripten)
Stop in /home/ur_0x6a73/projects/candle-test/candle
`
So it seems like it's just some small syntax differences.

**Comment by EvilPudding** [comment]
More issues could surface by fixing that one. The message isn't making much sense though, the `emscripten` rule doesn't use `CC` anywhere.

**Comment by ghost** [comment]
I've managed to make the makefile work for BSD (partially), but it seems like it would be counter-productive to maintain two different versions of the Makefile, as I didn't manage to make it run both on the GNU and the BSD version of Make. In order to make these work on both, you'd have to hardcode source and object filenames. I'd advise towards switching to some light build system that can either compile the code by itself or output both BSD and GNU makefiles. Moreover, most BSD users simply install gmake from the ports system, so it isn't really a problem to just use gmake on them. However, if you want to use the traditional multi-makefile system, here's how to get it to work:

The emscripten thing was problematic because in BSD version this code doesn't work:
```
emscripten: CC = emcc
emscripten: LD = emcc
emscripten: AR = emar
```
You have to replace it with this, GNU-incompatible code:
```
.if make(emscripten)
CC = emcc
LD = emcc
AR = emar
.endif
```

Further changes are replacing $(wildcard) thing with BSD shell commands (there's no other way AFAIK):
`${:!ls *.c!}`
Patsubst can be replace by the ```{variable:C/pattern/replacement/g}``` thing (which uses regular expressions), further explained in the official OpenBSD make manpage. It's a BSD extension though, so it won't work on GNU systems either.

**Comment by EvilPudding** [comment]
> I'd advise towards switching to some light build system

Is there any specific one you'd recommend? Like I said, I was planning on replacing the whole build system so that I wouldn't need a separate windows makefile.

**Comment by ghost** [comment]
To be honest, I'd recommend to try out Meson and see if it fits your vision of the build process.

**Pull request merged**
